//ParaClass.getDay(2);
public class ParaClass {
    public static String getDay(integer dayNumber){
        String day='';
        switch on dayNumber{
            when 0{
                day='sunday';
            }
            when 1{
                day='monday';
            }when 2{
                day='tuesday';
            }
            when 3{
                day='wednesday';
            }
            when 4{
                day='thurday';
            }
            when 5{
                day='friday';
            }
            when else{
                    day='invalid day';
                }
            }
            return day;
        }
    
    public integer getDay(integer num,String n2){
       return num;
    }
    }